### ISSUE TITLE
panicked at 'arithmetic operation overflowed'

### ISSUE THREAD

**Issue by vinipsmaker** [meqif/rust-utp#11]
I got luck to catch a panic while debugging on OS X: https://travis-ci.org/maidsafe/crust/jobs/76457152#L286

The failing code: https://github.com/meqif/rust-utp/blob/07dd46169e515e842c225d5bb5d1c3f63c870111/src/util.rs#L7

Any clue?

**Comment by meqif** [comment]
Thank you for the bug report.

That happens occasionally, although I haven't been able to pinpoint the exact conditions that trigger this bug. `time::get_time` should be returning the seconds and nanoseconds since the UNIX epoch, which doesn't jump around. Anyway, hopefully it's fixed now.

Please reopen the issue (or comment, if you can't reopen it) if you see that bug again. I may not answer right away since I'm on holiday.
