### ISSUE TITLE
Failing to build on ARM

### ISSUE THREAD

**Issue by vinipsmaker** [meqif/rust-utp#19]
crate `nix` not found. More details at <https://github.com/maidsafe/crust/issues/378#issuecomment-151083553>.

[I see this crate is only used to implement timeouts](https://github.com/meqif/rust-utp/blob/14f7ed7c3bef79248989f74cd3f1c69213c681d3/src/with_read_timeout.rs#L20-L22). Could we replace it for a more portable solution like [set_read_timeout](https://doc.rust-lang.org/stable/std/net/struct.UdpSocket.html#method.set_read_timeout)?

**Comment by meqif** [comment]
That's the plan. The current state was merely a stop-gap solution until `set_read_timeout` was re-introduced (after being removed from the standard libraries on 1.0) and reached the stable release, which I've been awaiting for a while.

Needless to say, the only reason the library isn't using `set_read_timeout` already is because I want the crate to always be compilable with the latest stable release. If I recall correctly, the Rust beta is promoted to stable on a 6-week schedule, which means 1.4 is coming out later this week.
