### ISSUE TITLE
Is there a plan to switch to MIO?

### ISSUE THREAD

**Issue by inetic** [meqif/rust-utp#23]
Hi Ricardo, this isn't really an "issue", just a question we have so feel free to close it. But, is there a plan to switch `rust-utp` to mio? I assume it would be a lot of rewrite, both, internally and also to the external API. Or do you think it would make more sense to start from scratch with a new library?

**Comment by meqif** [comment]
Hi Peter!

I'm currently testing a partial rewrite with mio. I don't think starting from scratch is necessarily better or even needed, since most of the code in `master` can be used with relatively minor changes.

I can't give any estimates, but suffice it to say that the rewrite is going well (apart from the occasional subtle annoyances that come with locking primitives).

In short: yes, there is a plan to switch to mio, and it's currently under way.

**Comment by inetic** [comment]
Thanks Ricardo, that is a great news.

**Comment by dirvine** [comment]
Do you have any update on this Ricardo, it seems a good step to increase efficiency.
